tap "bufbuild/buf"
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
brew "certifi"
brew "ansible"
brew "node"
brew "ansible-language-server"
brew "bash-language-server"
brew "black", restart_service: true
brew "gcc"
brew "btop"
brew "glib"
brew "calc"
brew "chezmoi"
brew "cloc"
brew "coreutils"
brew "cppcheck"
brew "curl"
brew "docker"
brew "docker-compose"
brew "dos2unix"
brew "unbound", restart_service: true
brew "harfbuzz"
brew "pango"
brew "ffmpeg"
brew "figlet"
brew "gatsby-cli"
brew "gdk-pixbuf"
brew "geoip"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-flow-avh"
brew "glab"
brew "openssl@1.1"
brew "gnu-indent"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "golangci-lint"
brew "gopls"
brew "librsvg"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hugo"
brew "imagemagick"
brew "ispell"
brew "kubectx"
brew "llvm"
brew "mage"
brew "markdown"
brew "mas"
brew "microplane"
brew "ncftp"
brew "nmap"
brew "pgformatter"
brew "pipx"
brew "qemu"
brew "prettier"
brew "protoc-gen-go"
brew "protoc-gen-go-grpc"
brew "pyenv"
brew "pygments"
brew "python-charset-normalizer"
brew "python-urllib3"
brew "python-requests"
brew "s3cmd"
brew "solargraph"
brew "source-highlight"
brew "sqlc"
brew "swift-format"
brew "telnet"
brew "wireshark", link: false
brew "termshark"
brew "the_silver_searcher"
brew "thefuck"
brew "tldr"
brew "tree-sitter"
brew "universal-ctags", args: ["HEAD"]
brew "util-linux"
brew "virtualenv"
brew "watch"
brew "wget"
brew "with-readline"
brew "yaml-language-server"
brew "yarn"
brew "zig"
brew "bufbuild/buf/buf"
brew "d12frosted/emacs-plus/emacs-plus@29"
cask "font-victor-mono"
cask "iterm2"
cask "rar"
cask "stats"
cask "tunnelblick"
cask "utm"
cask "vnc-viewer"
cask "wireshark"
mas "Developer", id: 640199958
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Playgrounds", id: 1496833156
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835
