"$schema" = 'https://starship.rs/config-schema.json'

[directory]
truncation_length = 5
truncation_symbol = '…/'
before_repo_root_style = 'red'
repo_root_style = 'bold cyan'

[status]
disabled = false

[sudo]
disabled = false

[buf]
symbol = "buf "

[cpp]
disabled = false

[git_branch]
ignore_branches = [ 'master', 'main']
always_show_remote = true
symbol = ' '

[git_commit]
tag_disabled = false

[git_metrics]
disabled = false

[golang]
version_format = "v${major}.${minor}"
detect_files = [ "go.mod", "go.work" ]

[python]
pyenv_version_name = true

[custom.sqlc]
symbol = "sqlc "
style = "bold blue"
detect_files = [ "sqlc.yml", "sqlc.yaml" ]


